FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.contacts.all.app.dev-8.0.0.016_Simrel_2018_09_M2.war /usr/local/tomcat/webapps/contacts.war

CMD ["catalina.sh", "run"]
