FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.widgets.ui.html.app.dev-8.0.0.016_Simrel_2018_09_M2.war /usr/local/tomcat/webapps/widgets.war

CMD ["catalina.sh", "run"]
